name: Tablet App Build

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/tablet/**'
      - 'packages/**'
      - '.github/workflows/tablet-build.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/tablet/**'
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint -F cerebral-tablet

      - name: Build
        run: pnpm run build -F cerebral-tablet

      - name: Test
        run: pnpm run test -F cerebral-tablet

      - name: Read package version
        id: version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Build Docker image and push to registry
        id: build
        uses: baerautotech/cerebral-deployment/.github/actions/build-with-kaniko@main
        with:
          image-name: 'cerebral/tablet:${{ steps.version.outputs.version }}'
          dockerfile: 'apps/tablet/Dockerfile'
          context: '.'

      - name: Generate SLSA provenance
        id: slsa
        uses: slsa-framework/slsa-github-generator/.github/actions/generator/generic/create-payload@v2.0.0
        with:
          command: create-payload
          digest: ${{ steps.build.outputs.image-digest }}
          name: cerebral/tablet

      - name: Also tag as latest on main branch
        if: github.ref == 'refs/heads/main'
        uses: baerautotech/cerebral-deployment/.github/actions/build-with-kaniko@main
        with:
          image-name: 'cerebral/tablet:latest'
          dockerfile: 'apps/tablet/Dockerfile'
          context: '.'
